name = "static-pdc"
compatibility_date = "2025-05-05"
main = "worker.js"

[site]
bucket = "/pdc-zip"

# Enable observability and logs
[observability]
enabled = true

# Custom domain: us.point.com (configured in Cloudflare dashboard)